name: MaxMORIX
favicon: null
layout_spectrum: 0.3709175332915038
typography_spectrum: 0.7774227045010775
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.899875643895939
  lightness: 0.5746411390136927
  saturation: 0.47836922761052847
  rhythmicContrast: 0.28800557111389935
purpose: []
